name: Build and deploy ASP.Net Core app to Azure Web App - FrameForge

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    env:
      DOTNET_ROOT: ${{ runner.tool_cache }}/dotnet

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'

      - name: Build solution
        run: dotnet build FrameForge/FrameForge/FrameForge.csproj --configuration Release

      - name: Publish project
        run: dotnet publish FrameForge/FrameForge/FrameForge.csproj -c Release -o ${{ env.DOTNET_ROOT }}/publish

      - name: Show publish folder contents
        run: ls -la ${{ env.DOTNET_ROOT }}/publish

      - name: Zip published output (flatten)
        run: |
          cd ${{ env.DOTNET_ROOT }}/publish
          zip -r ../publish.zip .

      - name: Upload artifact for deploy job
        uses: actions/upload-artifact@v4
        with:
          name: publish-zip
          path: ${{ env.DOTNET_ROOT }}/publish.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: publish-zip

      - name: Show files after download
        run: ls -la

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_9CDC522092A04DCE9FDFD0F7FC6F1824 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_440F1154EE924DCD8A5388DD736AFA86 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_FF8D64F495D6446E8604E55DA80795B3 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'FrameForge'
          slot-name: 'Production'
          package: 'publish.zip'
