name: Build and deploy ASP.Net Core app to Azure Web App - FrameForge

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'

      - name: Build solution
        run: dotnet build FrameForge/FrameForge.sln --configuration Release

      - name: Publish app
        run: dotnet publish FrameForge/FrameForge.sln -c Release -o ${{env.DOTNET_ROOT}}/publish

      - name: Zip publish folder contents
        run: |
          cd ${{env.DOTNET_ROOT}}/publish
          zip -r ../../publish.zip .  # zip contents only, place zip two levels up

      - name: Upload zipped artifact
        uses: actions/upload-artifact@v4
        with:
          name: publish-zip
          path: publish.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download publish zip artifact
        uses: actions/download-artifact@v4
        with:
          name: publish-zip
          path: .

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'FrameForge'
          slot-name: 'Production'
          package: 'publish.zip'
