name: Build and deploy ASP.Net Core app to Azure Web App - FrameForge

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'

      - name: Build with dotnet
        run: dotnet build FrameForge/FrameForge.sln --configuration Release

      - name: Publish app to folder
        run: dotnet publish FrameForge/FrameForge.sln -c Release -o ./publish

      - name: Create ZIP archive of published app
        run: zip -r publish.zip ./publish/*

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: publish.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read # This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_9CDC522092A04DCE9FDFD0F7FC6F1824 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_440F1154EE924DCD8A5388DD736AFA86 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_FF8D64F495D6446E8604E55DA80795B3 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'FrameForge'
          slot-name: 'Production'
          package: 'publish.zip'
